local L = LibStub("AceLocale-3.0"):NewLocale("GridTargets", "enUS", true)

L["GridTargets"] = true
L["mob health"] = true
L["mob target"] = true
L["mob cast"] = true
L["mob aggro"] = true
L["mob target indikator"] = true
L["Use class color"] = true
L["Color target based on class."] = true
L["Ignore self"] = true
L["Ignore tanks"] = true
L["Does not display if you are the target"] = true
L["Does not display if a tank is the target (needs oRA)."] = true
L["Use threat color"] = true
L["Color health based on your threat on the mob."] = true
L["Tanking"] = true
L["Color for Tanking."] = true
L["Almost lost"] = true
L["Color for still tanking but almost lost."] = true
L["Lost aggro"] = true
L["Color for not tanking."] = true
L["Color by mob ID"] = true
L["Color health based on the mobs id. This tries to give every mob a distinct color."] = true
L["Show only special casts"] = true
L["If enabled only the special casts listed below are displayed."] = true
L["Add special cast"] = true
L["Adds the cast with the passed name to the list of special casts."] = true
L["<cast name>"] = true
L["Removes this cast."] = true
L["Remove"] = true
L["Remove casts from the list of special casts."] = true