-- Pawn by Vger-Azjol-Nerub
-- www.vgermods.com
-- © 2006-2015 Green Eclipse.  This mod is released under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 license.
-- See Readme.htm for more information.

-- 
-- Italian resources
------------------------------------------------------------

local function PawnUseThisLocalization()
PawnLocal =
{
	AsteriskTooltipLine = "|TInterface\\AddOns\\Pawn\\Textures\\Question:0|t Effetti speciali non inclusi nel valore.",
	AverageItemLevelIgnoringRarityTooltipLine = "Livello oggetti medio",
	BackupCommand = "riserva",
	BaseValueWord = "base",
	CogwheelName = "Ingranaggio",
	CopyScaleEnterName = "Inserisci un nome per la tua nuova formula, copiato da %s:",
	CorrectGemsValueCalculationMessage = "   -- Le gemme corrette avranno valore: %g",
	CrystalOfFearName = "Cristallo della Paura",
	DebugOffCommand = "debug off",
	DebugOnCommand = "debug on",
	DecimalSeparator = ",",
	DeleteScaleConfirmation = "Sei sicuro di voler cancellare %s? Questa operazione non \195\168 reversibile. Scrivi \"%s\" per confermare:",
	DidntUnderstandMessage = "   (?) Non ho capito \"%s\".",
	EnchantedStatsHeader = "(Valore corrente)",
	EngineeringName = "Ingegneria",
	ExportAllScalesMessage = "Premi Ctrl+C per copiare le etichette della tua formula, crea un file sul tuo computer per salvarle come backup, quindi premi Ctrl+V per incollarle.",
	ExportScaleMessage = "Premi Ctrl+C per copiare la seguente etichetta della formula per |cffffffff%s|r, e quindi premi Ctrl+V per incollarla pi\195\185 tardi.",
	FailedToGetItemLinkMessage = "   Errore nel prendere il link dell'oggetto dal tooltip. Questo potrebbe essere per un conflitto di addon.",
	FailedToGetUnenchantedItemMessage = "   Errore nel prendere il valore base dell'oggetto. Questo potrebbe essere per un conflitto di addon.",
	FoundStatMessage = "   %d %s",
	GemColorList1 = "%d %s",
	GemColorList2 = "%d %s o %s",
	GemColorList3 = "%d di qualsiasi colore",
	GenericGemLink = "|Hitem:%d|h[Gemma %d]|h",
	GenericGemName = "(Gemma %d)",
	HiddenScalesHeader = "Altri bilanciamenti",
	ImportScaleMessage = "Premi Ctrl+v per incollare qui l'etichetta della formula che hai copiato da un'altra fonte:",
	ImportScaleTagErrorMessage = "Pawn non capisce quel'etichetta della formula. Hai copiato tutta l'etichetta? Prova a copiarla e incollarla nuovamente:",
	ItemIDTooltipLine = "ID oggetto",
	ItemLevelTooltipLine = "Livello oggetto",
	LootUpgradeAdvisorHeader = "Clicca per paragonare con i tuoi oggetti.|n",
	LootUpgradeAdvisorHeaderMany = "|TInterface\\AddOns\\Pawn\\Textures\\UpgradeArrow:0|t Questo oggetto \195\168 un miglioramento per %d formule. Clicca per paragonare con i tuoi oggetti",
	MissocketWorthwhileMessage = "   -- Ma \195\168 meglio utilizzare solo gemme %s :",
	NeedNewerVgerCoreMessage = "Pawn ha bisogno di una nuova versione di VgerCore. Per favore usa la versione di VgerCore inclusa con Pawn.",
	NewScaleDuplicateName = "Una formula con questo nome esiste gi\195\160. Inserisci un nome per la tua formula:",
	NewScaleEnterName = "Inserisci un nome per la tua formula:",
	NewScaleNoQuotes = "Una formula non pu\195\178 avere \" all'interno del nome. Inserisci un nome per la tua formula:",
	NormalizationMessage = "   -- Normalizzato dividendo per %g",
	NoScale = "(nessuna)",
	NoScalesDescription = "Per cominciare, importa una formula o creane una nuova.",
	NoStatDescription = "Scegli una statistica dalla lista a sinistra.",
	Or = "o",
	RenameScaleEnterName = "Inserisci un nuovo nome per %s:",
	SocketBonusValueCalculationMessage = "   -- Il bonus d'incavo avr\195\160 valore: %g",
	StatNameText = "1 |cffffffff%s|r ha valore:",
	ThousandsSeparator = ".",
	TooltipBestAnnotation = "%s  |cff8ec3e6(migliore)|r",
	TooltipBestAnnotationSimple = "%s  il migliore per te",
	TooltipBigUpgradeAnnotation = "%s  |TInterface\\AddOns\\Pawn\\Textures\\UpgradeArrow:0|t|cff00ff00 miglioramento%s|r",
	TooltipSecondBestAnnotation = "%s  |cff8ec3e6(secondo migliore)|r",
	TooltipSecondBestAnnotationSimple = "%s  il secondo migliore per te",
	TooltipUpgradeAnnotation = "%s  |TInterface\\AddOns\\Pawn\\Textures\\UpgradeArrow:0|t|cff00ff00+%.0f%% miglioramento%s|r",
	TooltipUpgradeFor1H = " per 1 mano",
	TooltipUpgradeFor2H = " per 2 mani",
	TooltipVersusLine = "%s|n  vs. |c%s%s|r",
	TotalValueMessage = "   ---- Totale: %g",
	UnenchantedStatsHeader = "(Valore di base)",
	Unusable = "(inutilizzabile)",
	UnusableStatMessage = "   -- %s \195\168 inutilizzabile, quindi mi fermo.",
	Usage = "Pawn by Vger-Azjol-Nerub\
www.vgermods.com\
 \
/pawn -- mostra o nasconde l'interfaccia di Pawn\
/pawn debug [ on | off ] -- spamma messaggi di debug nella console\
/pawn backup -- fa il backup delle tue formule in etichette di formula\
 \
Per maggiori informazioni su come personalizzare Pawn, per favore leggere il file (Readme.htm) inclusa con l'addon.\
",
	ValueCalculationMessage = "   %g %s x %g ognuno = %g",
	VisibleScalesHeader = "Formule di %s",
	Stats = {
		AgilityInfo = "Agilit\195\160. Aumenta la potenza d'attacco per alcune classi.",
		Ap = "Potenza d'attacco",
		ApInfo = "Potenza d'attacco. Non presente direttamente sulla maggior parte degli oggetti. Non include la potenza d'attacco che ottieni dalla Forza o dall'Agilit\195\160.",
		ArmorInfo = "Armatura. Non include il bonus di armatura specifico del difensore",
		ArmorTypes = "Tipi d'armatura",
		AvoidanceInfo = "Elusione. Riduce i danni subiti dagli attacchi ad area d'effetto.",
		BonusArmorInfo = "Armatura bonus. Non include il valore di armatura base su tutte le armature. Questo valore dovrebbe assumere almeno lo stesso valore di Armatura. (Parata e Schivata su oggetti di basso livello vengono trattate come Armatura bonus)",
		Cloth = "Stoffa",
		ClothInfo = "Punti da assegnare se l'oggetto \195\168 in stoffa",
		Crit = "Critico",
		CritInfo = "Critico. Aumenta la possibilit\195\160 che i tuoi attacchi e le tue cure colpiscano con potenza maggiore.",
		DpsInfo = "Danno dell'arma al secondo. (Se vuoi dare un valore diverso per i differenti tipi di arma, vedi la sezione \"Attributi speciali delle armi\").",
		HasteInfo = "Celerit\195\160. Aumenta la velocit\195\160 con cui le tue magie vengono lanciate e le risorse si rigenerano.",
		IndestructibleInfo = "Indistruttibile. Previene che il tuo equipaggiamento prenda danni d'uso.",
		IndestructibleIs = "Essere |cffffffffindistruttibile|r vale:",
		IntellectInfo = "Intelletto. Aumenta potenza magica per alcune classi.",
		Leather = "Pelle",
		LeatherInfo = "Punti da assegnare se l'oggetto \195\168 in pelle",
		LeechInfo = "Ritorno vitale. Rigenera parte della salute quando infliggi danni o fornisci cure.",
		Mail = "Maglia",
		MailInfo = "Punti da assegnare se l'oggetto \195\168 in maglia",
		MasteryInfo = "Maestria. Aumenta l'abilit\195\160 unica della tua specializzazione di classe",
		MetaSocket = "Incavo prismatico",
		MetaSocketInfo = "Un incavo prismatico, sia pieno che vuoto. Assegna punti extra per elmi che hanno un incavo prismatico per compensare l'effetto speciale della gemma prismatica.",
		MinorStats = "Attributi minori",
		MovementSpeedInfo = "Velocit\195\160 di movimento. F\195\160 si che il tuo personaggio corra pi\195\185 veloce.",
		MultistrikeInfo = "Replicazione. Aumenta la possibilit\195\160 che i tuoi attacchi e le tue magie di cura colpiscano il bersaglio due volte in pi\195\185 a potenza ridotta.",
		Plate = "Piastre",
		PlateInfo = "Punti da assegnare se l'oggetto \195\168 in piastre",
		PrimaryStats = "Attributi primari",
		PvPPower = "Potenza PvP",
		PvPPowerInfo = "Potenza PvP. Permette alle tue abilit\195\160 di infliggere pi\195\185 danni agli altri giocatori (ma non creature), e alle tue cure di curare di pi\195\185 gli altri giocatori in alcune situazioni di PvP.",
		PvPResilience = "Resilienza PvP",
		PvPResilienceInfo = "Resilienza PvP. Riduce il danno che subisci dagli attacchi degli altri giocatori. Efficace solo contro gli altri giocatori.",
		PvPStats = "Attributi PvP",
		SecondaryStats = "Attributi secondari",
		Shield = "Scudo",
		ShieldInfo = "Punti da assegnare se l'oggetto \195\168 uno scudo.",
		Sockets = "Incavi",
		SpecialWeaponStats = "Attributi speciali delle armi",
		SpeedBaseline = "Velocit\195\160 di base",
		SpeedBaselineInfo = "Non \195\168 un attributo che appare visibilmente su un'arma, questo numero \195\168 sottratto dall'attributo di velocit\195\160 prima di moltiplicarlo per il valore di scala.",
		SpeedBaselineIs = "|cffffffffVelocit\195\160 di base|r \195\168:",
		SpeedInfo = "Velocit\195\160 dell'arma, in secondi per colpo. (Se preferisci armi veloci, questo numero dovrebbe assumere valori negativi. Vedi anche \"velocit\195\160 di base\" nella sezione \"Attributi speciali delle armi\").",
		SpeedIs = "1 secondo di |cffffffffvelocit\195\160 del colpo|r vale:",
		SpellPower = "Potenza magica",
		SpellPowerInfo = "Potenza magica. Presente su armi da incantatore. Aumenta il danno e le cure dei tuoi incantesimi. Non include la potenza magica che ricevi dall'Intelletto.",
		SpiritInfo = "Spirito. Aumenta la rigenerazione del mana per i curatori.",
		StaminaInfo = "Tempra. Aumenta la tua vita.",
		StrengthInfo = "Forza. Aumenta la potenza d'attacco per alcune classi.",
		VersatilityInfo = "Versatilit\195\160. Aumenta i danni inflitti e le cure fornite, e riduce i danni subiti.",
		WeaponMainHandDps = "MH: DPS",
		WeaponMainHandDpsInfo = "Danno dell'arma al secondo, solo per l'arma della mano primaria.",
		WeaponMainHandMaxDamage = "MH: danno massimo",
		WeaponMainHandMaxDamageInfo = "Danno massimo dell'arma, solo per l'arma della mano primaria.",
		WeaponMainHandMinDamage = "MH: danno minimo",
		WeaponMainHandMinDamageInfo = "Danno minimo dell'arma, solo per l'arma della mano primaria.",
		WeaponMainHandSpeed = "MH: velocit\195\160",
		WeaponMainHandSpeedInfo = "Velocit\195\160 dell'arma, solo per l'arma della mano primaria.",
		WeaponMaxDamage = "Danno massimo",
		WeaponMaxDamageInfo = "Danno massimo dell'arma",
		WeaponMeleeDps = "Mischia: DPS",
		WeaponMeleeDpsInfo = "Danno da mischia al secondo, solo per armi da mischia.",
		WeaponMeleeMaxDamage = "Mischia: danno massimo",
		WeaponMeleeMaxDamageInfo = "Danno massimo dell'arma, solo per armi da mischia.",
		WeaponMeleeMinDamage = "Mischia: danno minimo",
		WeaponMeleeMinDamageInfo = "Danno minimo dell'arma, solo per armi da mischia.",
		WeaponMeleeSpeed = "Mischia: velocit\195\160",
		WeaponMeleeSpeedInfo = "Velocit\195\160 dell'arma, solo per armi da mischia.",
		WeaponMinDamage = "Danno minimo",
		WeaponMinDamageInfo = "Danno minimo dell'arma",
		WeaponOffHandDps = "OH: DPS",
		WeaponOffHandDpsInfo = "Danno dell'arma al secondo, solo per l'arma della mano secondaria.",
		WeaponOffHandMaxDamage = "OH: danno massimo",
		WeaponOffHandMaxDamageInfo = "Danno massimo dell'arma, solo per l'arma della mano secondaria.",
		WeaponOffHandMinDamage = "OH: danno minimo",
		WeaponOffHandMinDamageInfo = "Danno minimo dell'arma, solo per l'arma della mano secondaria.",
		WeaponOffHandSpeed = "OH: velocit\195\160",
		WeaponOffHandSpeedInfo = "Velocit\195\160 dell'arma, solo per l'arma della mano secondaria.",
		WeaponOneHandDps = "1H: DPS",
		WeaponOneHandDpsInfo = "Danno dell'arma al secondo, solo per armi segnate ad una mano, non include armi per la mano principale o per la mano secondaria.",
		WeaponOneHandMaxDamage = "1H: danno massimo",
		WeaponOneHandMaxDamageInfo = "Danno massimo dell'arma, solo per armi segnate ad una mano, non include armi per la mano principale o per la mano secondaria.",
		WeaponOneHandMinDamage = "1H: danno minimo",
		WeaponOneHandMinDamageInfo = "Danno minimo dell'arma, solo per armi segnate ad una mano, non include armi per la mano principale o per la mano secondaria.",
		WeaponOneHandSpeed = "1H: velocit\195\160",
		WeaponOneHandSpeedInfo = "Velocit\195\160 dell'arma, solo per armi segnate ad una mano, non include armi per la mano principale o per la mano secondaria.",
		WeaponRangedDps = "A distanza: DPS",
		WeaponRangedDpsInfo = "Danno dell'arma al secondo, solo per armi a distanza.",
		WeaponRangedMaxDamage = "A distanza: danno massimo",
		WeaponRangedMaxDamageInfo = "Danno massimo dell'arma, solo per armi a distanza.",
		WeaponRangedMinDamage = "A distanza: danno minimo",
		WeaponRangedMinDamageInfo = "Danno minimo dell'arma, solo per armi a distanza.",
		WeaponRangedSpeed = "A distanza: velocit\195\160",
		WeaponRangedSpeedInfo = "Velocit\195\160 dell'arma, solo per armi a distanza.",
		WeaponStats = "Attributi dell'arma",
		WeaponTwoHandDps = "2H: DPS",
		WeaponTwoHandDpsInfo = "Danno dell'arma al secondo, solo per armi a due mani.",
		WeaponTwoHandMaxDamage = "2H: danno massimo",
		WeaponTwoHandMaxDamageInfo = "Danno massimo dell'arma, solo per armi a due mani.",
		WeaponTwoHandMinDamage = "2H: danno minimo",
		WeaponTwoHandMinDamageInfo = "Danno minimo dell'arma, solo per armi a due mani.",
		WeaponTwoHandSpeed = "2H: velocit\195\160",
		WeaponTwoHandSpeedInfo = "Velocit\195\160 dell'arma, solo per armi a due mani.",
		WeaponType1HAxe = "Ascia: 1H",
		WeaponType1HAxeInfo = "Punti da assegnare se l'arma \195\168 un'ascia ad una mano.",
		WeaponType1HMace = "Mazza: 1H",
		WeaponType1HMaceInfo = "Punti da assegnare se l'arma \195\168 una mazza ad una mano.",
		WeaponType1HSword = "Spada: 1H",
		WeaponType1HSwordInfo = "Punti da assegnare se l'arma \195\168 una spada ad una mano.",
		WeaponType2HAxe = "Ascia: 2H",
		WeaponType2HAxeInfo = "\"Punti da assegnare se l'arma \195\168 un'ascia a due mani.",
		WeaponType2HMace = "Mazza: 2H",
		WeaponType2HMaceInfo = "Punti da assegnare se l'arma \195\168 una mazza a due mani.",
		WeaponType2HSword = "Spada: 2H",
		WeaponType2HSwordInfo = "Punti da assegnare se l'arma \195\168 una spada a due mani.",
		WeaponTypeBow = "Acro",
		WeaponTypeBowInfo = "Punti da assegnare se l'arma \195\168 un arco.",
		WeaponTypeCrossbow = "Balestra",
		WeaponTypeCrossbowInfo = "Punti da assegnare se l'arma \195\168 una balestra.",
		WeaponTypeDagger = "Pugnale",
		WeaponTypeDaggerInfo = "Punti da assegnare se l'arma \195\168 un pugnale.",
		WeaponTypeFistWeapon = "Tirapugni",
		WeaponTypeFistWeaponInfo = "Punti da assegnare se l'arma \195\168 un tirapugni.",
		WeaponTypeFrill = "Accessorio",
		WeaponTypeFrillInfo = "Punti da assegnare se l'arma \195\168 un accessorio. Non si applica a scudi o armi.",
		WeaponTypeGun = "Arma da fuoco",
		WeaponTypeGunInfo = "Punti da assegnare se l'arma \195\168 un'arma da fuoco.",
		WeaponTypeOffHand = "Arma della mano secondaria",
		WeaponTypeOffHandInfo = "Punti da assegnare se l'arma \195\168 un oggetto che pu\195\178 essere tenuto solo nella mano secondaria. Non si applica per accessori, scudi o armi che possono essere tenute in entrambe le mani.",
		WeaponTypePolearm = "Arma in asta",
		WeaponTypePolearmInfo = "Punti da assegnare se l'arma \195\168 un'arma in asta.",
		WeaponTypes = "Tipi di armi",
		WeaponTypeStaff = "Bastone",
		WeaponTypeStaffInfo = "Punti da assegnare se l'arma \195\168 un bastone",
		WeaponTypeWand = "Bacchetta",
		WeaponTypeWandInfo = "Punti da assegnare se l'arma \195\168 una bacchetta.",
	},
	TooltipParsing = {
		Agility = "^%+?([-%d%.,]+) [Aa]gilit\195\160$",
		AllStats = "^%+?([%d%.,]+) a tutti gli attributi$",
		Ap = "^%+?([%d%.,]+) [Pp]otenza d'attacco$",
		Armor = "^%+?([%d%.,]+) [Aa]rmatura$",
		Armor2 = "UNUSED",
		Avoidance = "^%+([%d%.,]+) Indice d'elusione$",
		Axe = "^Ascia$",
		BagSlots = "^%d+ Scomparto .+$",
		BladesEdgeMountains = "^Montagne Spinaguzza$",
		BonusArmor = "^%+([%d%.,]+) [Aa]rmatura [Bb]onus$",
		Bow = "^Acro$",
		ChanceOnHit = "Probabilit\195\160 d'impatto:",
		Charges = "^.+ Cariche?$",
		Cloth = "^Stoffa$",
		CooldownRemaining = "^Recupero restante:",
		Crit = "^%+?([%d%.,]+) Indice di [Cc]ritico%.?$",
		Crit2 = "UNUSED",
		Crossbow = "^Balestra$",
		Dagger = "^Pugnale$",
		Design = "Progetto:",
		DisenchantingRequires = "^[Rr]ichiede [Dd]isincantamento",
		Dodge = "^%+?([%d%.,]+) Schivata$",
		Dodge2 = "UNUSED",
		Dps = "^%(([%d%.,]+) [Dd]anni per [Ss]econdo%)$",
		DpsAdd = "^Aggiunge ([%d%.,]+) [Dd]anni per [Ss]econdo",
		Duration = "^Durata:",
		Elite = "^[E\195\137]lite$",
		EnchantmentArmorKit = "^Rinforzato %(%+([%d%.,]+) [Aa]rmatura%)$",
		EnchantmentCounterweight = "^Contrappeso %(%+([%d%.,]+) [Ii]ndice di [Cc]elerit\195\160%)",
		EnchantmentFieryWeapon = "^Armardente$",
		EnchantmentHealth = "^%+([%d%.,]+) [Ss]alute$",
		EnchantmentHealth2 = "UNUSED",
		EnchantmentLivingSteelWeaponChain = "^Catena per [Aa]rma d'[Aa]cciaio [Vv]ivente$",
		EnchantmentPyriumWeaponChain = "^Catena per [Aa]rma di [Pp]irio$",
		EnchantmentTitaniumWeaponChain = "^Catena per [Aa]rma di [Tt]itanio$",
		Equip = "Equipaggia:",
		FistWeapon = "^Tirapugni$",
		Flexible = "^Flessibile$",
		Formula = "Formula:",
		Gun = "^Arma da [Ff]uoco$",
		Haste = "^%+?([%d%.,]+) [Ii]ndice di [Cc]elerit\195\160$",
		Haste2 = "UNUSED",
		HeirloomLevelRange = "^Richiede un livello da %d+ a (%d+)",
		HeirloomXpBoost = "^Equipaggia: Aumenta l'esperienza",
		HeirloomXpBoost2 = "UNUSED",
		Heroic = "^Eroico$",
		HeroicElite = "^Eroico [E\195\137]lite$",
		HeroicThunderforged = "^Eroico Tuonoforgiat[oa]$",
		HeroicWarforged = "^Eroico Guerraforgiat[oa]$",
		Hp5 = "^%+?([%d%.,]+) Salute ogni 5 s.$",
		Hp52 = "UNUSED",
		Hp53 = "UNUSED",
		Hp54 = "UNUSED",
		Intellect = "^%+?([-%d%.,]+) [Ii]ntelletto$",
		Leather = "^Cuoio$",
		Leech = "^%+([%d%.,]+) [Ii]ndice di [Rr]itorno [Vv]itale$",
		Mace = "^Mazza$",
		Mail = "^Maglia$",
		Manual = "Manuale:",
		Mastery = "^%+?([%d%.,]+) [Ii]ndice di [Mm]aestria$",
		Mastery2 = "UNUSED",
		MetaGemRequirements = "|cff%x%x%x%x%x%xRichiede",
		MovementSpeed = "^%+([%d%.,]+) [Vv]elocit\195\160$",
		MultiStatSeparator1 = "e",
		Multistrike = "^%+([%d%.,]+) [Ii]ndice di [Rr]eplicazione$",
		NormalizationEnchant = "^Incantato: (.*)$",
		OnlyFitsInMetaGemSlot = "^\"Compatibile solo con un incavo [Mm]eta.\"$",
		Parry = "^%+?([%d%.,]+) [Ii]ndice di [Pp]arata$",
		Parry2 = "UNUSED",
		Pattern = "Modello:",
		Plans = "Progetto:",
		Plate = "^Piastre$",
		Polearm = "^Arma ad asta$",
		PvPPower = "^%+?([%d%.,]+) Potenza PvP$",
		RaidFinder = "^Ricerca delle Incursioni$",
		Recipe = "Ricetta:",
		Requires2 = "UNUSED",
		Resilience = "^%+?([%d%.,]+) Resilienza PvP$",
		Resilience2 = "UNUSED",
		Schematic = "Schema:",
		Scope = "^Mirino %(%+([%d%.,]+) Danni%)$",
		ScopeCrit = "^Mirino %(%+([%d%.,]+) Indice di Critico%)$",
		ScopeRangedCrit = "^%+?([%d%.,]+) Indice di Critico$",
		Season = "^Stagione",
		ShadowmoonValley = "^Valle di Torvaluna$",
		Shield = "^Scudo$",
		SocketBonusPrefix = "Bonus incavo:",
		Speed = "^Velocit\195\160 ([%d%.,]+)$",
		Speed2 = "UNUSED",
		SpellPower = "^%+?([%d%.,]+) Potenza [Mm]agica$",
		Spirit = "^%+?([-%d%.,]+) Spirito$",
		Staff = "^Bastone$",
		Stamina = "^%+?([-%d%.,]+) Tempra$",
		Strength = "^%+?([-%d%.,]+) Forza$",
		Sword = "^Spada$",
		TempestKeep = "^Forte Tempesta$",
		TemporaryBuffMinutes = "^.+%(%d+ min%)",
		TemporaryBuffSeconds = "^.+%(%d+ sec%)",
		Thunderforged = "^Tuonoforgiat[oa]$",
		Timeless = "^Senza Tempo$",
		UpgradeLevel = "^Aumenta [Ll]ivello:",
		Use = "Usa:",
		Versatility = "^%+([%d%.,]+) Indice di [Vv]ersatilit\195\160$",
		Wand = "^Bacchetta$",
		Warforged = "^Guerraforgiat[oa]$",
		WeaponDamage = "^([%d%.,]+) %- ([%d%.,]+) [Dd]ann[oi]$",
		WeaponDamageArcane = "^%+?([%d%.,]+) %- ([%d%.,]+) [Dd]ann[oi] [Dd]a [Aa]rcano$",
		WeaponDamageArcaneExact = "^%+?([%d%.,]+) [Dd]ann[oi] [Dd]a [Aa]rcano$",
		WeaponDamageEnchantment = "^%+?([%d%.,]+) Dann[oi] dell'[Aa]rma$",
		WeaponDamageEquip = "^Equip: %+?([%d%.,]+) Dann[oi] dell'[Aa]rma%.$",
		WeaponDamageExact = "^%+?([%d%.,]+) Dann[oi]$",
		WeaponDamageFire = "^%+?([%d%.,]+) %- ([%d%.,]+) [Dd]ann[oi] [Dd]a [Ff]uoco$",
		WeaponDamageFireExact = "^%+?([%d%.,]+) Dd]ann[oi] [Dd]a [Ff]uoco$",
		WeaponDamageFrost = "^%+?([%d%.,]+) %- ([%d%.,]+) [Dd]ann[oi] [Dd]a [Gg]elo$",
		WeaponDamageFrostExact = "^%+?([%d%.,]+) [Dd]ann[oi] [Dd]a [Gg]elo$",
		WeaponDamageHoly = "^%+?([%d%.,]+) %- ([%d%.,]+) [Dd]ann[oi] [Dd]a [Ss]acro$",
		WeaponDamageHolyExact = "^%+?([%d%.,]+) [Dd]ann[oi] [Dd]a [Ss]acro$",
		WeaponDamageNature = "^%+?([%d%.,]+) %- ([%d%.,]+) [Dd]ann[oi] [Dd]a [Nn]atura$",
		WeaponDamageNatureExact = "^%+?([%d%.,]+) [Dd]ann[oi] [Dd]a [Nn]atura$",
		WeaponDamageShadow = "^%+?([%d%.,]+) %- ([%d%.,]+) [Dd]ann[oi] [Dd]a [Oo]mbra$",
		WeaponDamageShadowExact = "^%+?([%d%.,]+) [Dd]ann[oi] [Dd]a [Oo]mbra$",
	},
	UI = {
		AboutHeader = "Informazioni su Pawn",
		AboutReadme = "Prima volta che utilizzi Pawn? Dai un'occhiata alla sezione Introduzione per avere delle informazioni di base.",
		AboutTab = "Informazioni su...",
		AboutTranslation = "Versione Italiana a cura di Licen",
		AboutVersion = "Versione %s",
		AboutWebsite = "Per altri mods di Vger, visita vgermods.com.\
\
Ottenuto il permesso di usare i pesi delle statistiche di Wowhead - si prega di dare il feedback sui valori di default direttamente a Wowhead.",
		CompareClearItems = "Azzera",
		CompareClearItemsTooltip = "Rimuovi entrambi gli oggetti da comparare.",
		CompareCogwheelSockets = "Incavo per Ingranaggi",
		CompareColoredSockets = "Incavo colorato",
		CompareEquipped = "Equipaggiato",
		CompareGemTotalValue = "Valore delle gemme",
		CompareHeader = "Compara gli oggetti usando %s",
		CompareMetaSockets = "Incavo Meta",
		CompareOtherHeader = "Altro",
		CompareShaTouchedSockets = "Toccata dallo Sha",
		CompareSlotEmpty = "(nessun oggetto)",
		CompareSocketBonus = "Bonus incavo",
		CompareSocketsHeader = "Incavi",
		CompareSpecialEffects = "Effetti speciali",
		CompareSwap = "\226\128\185 Scambia \226\128\186",
		CompareSwapTooltip = "Scambia l'oggetto a sinistra con l'oggetto a destra.",
		CompareTab = "Compara",
		CompareVersus = "\226\128\148vs.\226\128\148",
		CompareWelcomeLeft = "Per cominciare prendi una formula dalla lista sulla sinistra.",
		CompareWelcomeRight = "Quindi trascina un oggetto in questo riquadro.\
\
Puoi confrontarlo con i tuoi oggetti esistenti usando le icone nell'angolo in basso a sinistra.",
		CompareYourBest = "Il tuo \195\168 migliore",
		GemsColorHeader = "Gemme %s",
		GemsHeader = "Gemme per %s",
		GemsNoneFound = "Non \195\168 stata trovata una gemma appropriata.",
		GemsQualityLevel = "Livello di qualit\195\160 della gemma",
		GemsQualityLevelTooltip = "Livello degli oggetti per i quali suggerire le gemme.\
\
Per esempio, se impostato a \"463\", Pawn suggerir\195\160 gemme adatte per oggetti di livello 463: bottini delle spedizioni eroiche di Mists of Pandaria.",
		GemsShowBest = "Mostra le migliori gemme disponibili",
		GemsShowBestTooltip = "Mostra le gemme migliori in termini assoluti disponibili per la formula attualmente selezionata. Alcune di queste gemme saranno troppo potenti per gli incavi di oggetti vecchi e di bassa qualit\195\160.",
		GemsShowForItemLevel = "Mostra le gemme consigliate per un oggetto di livello:",
		GemsShowForItemLevelTooltip = "Mostra le gemme che Pawn consiglia per la formula attualmente selezionata e un oggetto di uno specifico livello.",
		GemsTab = "Gemme",
		GemsWelcome = "Seleziona una formula sulla sinistra per vedere le gemme che Pawn consiglia.",
		HelpHeader = "Benvenuto su Pawn!",
		HelpTab = "Introduzione",
		HelpText = "Pawn calcola i punteggi per i tuoi oggetti basandosi sulle statistiche possedute dall'oggetto. Utilizza questi punteggi per determinare quale oggetto \195\168 migliore, ed identifica gli oggetti che potrebbero migliorare il tuo equipaggiamento.\
\
\
Ogni oggetto avr\195\160 un punteggio per ogni \"formula\" attiva per il tuo personaggio. Una formula ha la lista delle statistiche importanti per te, e quanti punti vale ogni statistica. In genere hai una formula per ogni specializzazione o ruolo della tua classe. I punteggi sono generalmente nascosti, ma puoi vedere come il punteggio per un oggetto \195\168 stato calcolato attraverso la sezione Compara.\
\
 \226\128\162 Puoi attivare o disattivare una formula facendo shift-click su di essa nella lista della sezione Formula.\
\
\
Pawn esce con una formula pre-costruita per ogni classe e specializzazione. Puoi anche creare la tua versione assegnando valori ad ogni statistica, importando una formula da internet o da uno strumento di simulazione, oppure condividere la formula con i compagni di gilda.\
\
\
|cff8ec3e6Prova queste funzionalit\195\160 una volta che avrai imparato le basi:|r\
 \226\128\162 Compara le statistiche di due oggetti usando la sezione Compara di Pawn.\
 \226\128\162 Fai tasto destro su di un link ad un oggetto per vedere come viene paragonato al tuo attuale oggetto.\
 \226\128\162 Fai una copia di una delle tue formule dalla sezione Formula, e personalizza i valori delle statistiche dalla sezione Valori.\
 \226\128\162 Trova nuove formule per la tua classe attraverso internet.\
 \226\128\162 Controlla il file readme per imparare di pi\195\185 sulle funzioni avanzate di Pawn.",
		InterfaceOptionsBody = "Clicca sul pulsante di Pawn per aprirlo. Puoi anche aprire Pawn dall'inventario o associando un tasto ad esso.",
		InterfaceOptionsWelcome = "Le opzioni di Pawn si trovano nella relativa interfaccia di Pawn.",
		InventoryButtonTooltip = "Clicca per aprire Pawn.",
		InventoryButtonTotalsHeader = "Totali per tutti gli oggetti equipaggiati:",
		KeyBindingCompareItemLeft = "Compara oggetto (sinistra)",
		KeyBindingCompareItemRight = "Compara oggetto (destra)",
		KeyBindingShowUI = "Attiva/Disattiva l'interfaccia di Pawn",
		OptionsAdvisorHeader = "Opzioni avvisi",
		OptionsAlignRight = "Allinea i valori a destra",
		OptionsAlignRightTooltip = "Abilita questa opzione per allineare i valori di Pawn e le informazioni di miglioramento al bordo destro della tooltip invece che a sinistra.",
		OptionsBlankLine = "Aggiungi una riga vuota prima dei valori",
		OptionsBlankLineTooltip = "Mantieni la tooltip dei tuoi oggetti estremamente ordinata abilitando questa opzione. Essa aggiunger\195\160 una riga vuota prima dei valori di Pawn.",
		OptionsButtonHidden = "Nascondilo",
		OptionsButtonHiddenTooltip = "Non mostrare il pulsante di Pawn nel pannello Info Personaggio.",
		OptionsButtonPosition = "Mostra il pulsante di Pawn:",
		OptionsButtonPositionLeft = "A sinistra",
		OptionsButtonPositionLeftTooltip = "Mostra il pulsante di Pawn nell'angolo in basso a sinistra del pannello Info Personaggio.",
		OptionsButtonPositionRight = "A destra",
		OptionsButtonPositionRightTooltip = "Mostra il pulsante di Pawn nell'angolo in basso a destra del pannello Info Personaggio.",
		OptionsColorBorder = "Colora il bordo delle finestre di dialogo per i miglioramenti",
		OptionsColorBorderTooltip = "Abilita questa opzione per cambiare in verde il colore del bordo della tooltip degli oggetti che sono un miglioramento. Disabilitala se interferisce con altri addons che cambiano i bordi delle finestre di dialogo.",
		OptionsCurrentValue = "Mostra sia il valore corrente che il valore base",
		OptionsCurrentValueTooltip = "Abilita questa opzione per far s\195\172 che Pawn mostri due valori per oggetto: il valore corrente, che riflette lo stato corrente di un oggetto con le gemme e gli incantamenti che possiede al momento ed incavi vuoti che non portano beneficio; il valore di base, che \195\168 ci\195\178 che Pawn mostra normalmente. Questa opzione non ha effetto se non si abilita la visualizzazione del valore degli oggetti nella tooltip.\
\
Dovresti comunque usare il valore di base per decidere tra due oggetti a livello massimo, ma il valore corrente pu\195\178 essere d'aiuto durante il leveling per semplificare ladecisione sul guadagno immediato di equipaggiare un nuovo oggetto senza gemme o incantamenti.",
		OptionsDebug = "Mostra informazioni di debug",
		OptionsDebugTooltip = "Se non sei sicuro di come Pawn calcoli i valori per un particolare oggetto, abilita questa opzione che permetter\195\160 a Pawn di spammare tutta una serie di dati 'utili' nella chat ogni qual volta passi il mouse sopra un oggetto. Queste informazioni includono quali statistiche Pawn pensi che l'oggetto abbia, quale parte dell'oggetto non capisce, e come le consideri per tutte le formule.\
\
Questa optione riempir\195\160 la tua chat velocemente, quindi la vorrai disabilitare quando avrai finito di investigare.\
\
Scorciatoie:\
/pawn debug on\
/pawn debug off",
		OptionsHeader = "Modifica le opzioni di Pawn",
		OptionsIgnoreGemsWhileLevelingCheck = "Ignora gli incavi su oggetti di basso livello",
		OptionsIgnoreGemsWhileLevelingCheckTooltip = "Abilita questa opzione per far s\195\172 che Pawn ignori gli incavi su oggetti di basso livello durante il calcolo del valore degli oggetti, dato che molti non sprecano tempo per incastonare oggetti mentre stanno ancora livellando. Un oggetto di \"basso livello\" \195\168 uno meno potente di quello che pu\195\178 essere ottenuto da una spedizione eroica al livello massimo.\
\
Se attivata, l'avviso dell'incavo di Pawn suggerir\195\160 la gemma appropriata per gli oggetti di basso livello, ma gli incavi verranno ignorati durante i calcoli e gli oggetti incastonati non verranno mostrati come un miglioramento.\
\
Se disattivata, Pawn calcoler\195\160 il valore per gli oggetti come se fossero incastonati in modo da massimizzare il valore dell'oggetto, senza badare al livello dell'oggetto.",
		OptionsInventoryIcon = "Show inventory icons",
		OptionsInventoryIconTooltip = "Enable this option to show inventory icons next to item link windows.",
		OptionsItemIDs = "Mostra ID oggetti",
		OptionsItemIDsTooltip = "Abilita questa optione per permettere a Pawn di mostrare gli ID degli oggetti che incontri, cos\195\172 come gli ID degli incantamenti e delle gemme.\
\
Ogni oggetto in World of Warcraft ha un numero ID associato ad esso. Questa informazione \195\168 generalmente utile solo agli autori di addons.",
		OptionsLootAdvisor = "Mostra l'avviso di miglioramento sul bottino",
		OptionsLootAdvisorTooltip = "Quando esce un bottino in una spedizione e questo \195\168 un miglioramento per il tuo personaggio, Pawn mostrer\195\160 un popup accanto alla finestra di tiro per il bottino informandoti del miglioramento.",
		OptionsOtherHeader = "Altre opzioni",
		OptionsQuestUpgradeAdvisor = "Mostra avviso per miglioramento da una missione",
		OptionsQuestUpgradeAdvisorTooltip = "Nel tuo diario delle missioni e quando parli con un PNG, se una delle ricompense della missione \195\168 un miglioramento per il tuo equipaggiamento corrente, Pawn mostrer\195\160 una freccia verde su quell'oggetto. Se nessuno degli oggetti \195\168 un miglioramento, Pawn mostrer\195\160 una pila di monete sull'oggetto che vale di pi\195\185 se venduto ad un mercante.",
		OptionsResetUpgrades = "Scansiona nuovamente l'equipaggiamento",
		OptionsResetUpgradesTooltip = "Pawn dimenticher\195\160 ci\195\178 che sa sui migliori oggetti che tu abbia mai equipaggiato, e scansioner\195\160 nuovamente il tuo equipaggiamento per fornire informazioni maggiormente aggiornate in futuro.\
\
Usa questa funzionalit\195\160 se pensi che Pawn stia fornendo degli scarsi suggerimenti di miglioramento come risultato di un oggetto che hai venduto, distrutto o che non usi pi\195\185. Questo avr\195\160 effetto su tutti i tuoi personaggi che usano Pawn.",
		OptionsSocketingAdvisor = "Mostra l'avviso per gli incavi",
		OptionsSocketingAdvisorTooltip = "Quando aggiungi gemme ad un oggetto, Pawn mostrer\195\160 un popup suggerendo le gemme che puoi aggiungere all'oggetto che massimizzeranno il suo potere. (Per vedere tutta la lista delle gemme suggerite per ogni colore, vedi la scheda Gemme, dove puoi anche personalizzare la qualit\195\160 delle gemme da usare.)",
		OptionsTab = "Opzioni",
		OptionsTooltipHeader = "Opzioni dei tooltip",
		OptionsTooltipUpgradesOnly = "Mostra solo miglioramenti",
		OptionsTooltipUpgradesOnlyTooltip = "Questa \195\168 l'opzione pi\195\185 semplice. Mostra solo la percentuale di miglioramento per gli oggetti che migliorerebbero il tuo attuale equipaggiamento, ed indica quali oggetti sono migliori per ogni formula. Non mostra nulla per oggetti meno potenti.\
\
|cff8ec3e6Fuoco:|r  |TInterface\\AddOns\\Pawn\\Textures\\UpgradeArrow:0|t |cff00ff00+10% di miglioramento|r\
\
...oppure...\
\
|cff8ec3e6Fuoco:  il migliore per te|r",
		OptionsTooltipValuesAndUpgrades = "Mostra il valore per la formula e la % di miglioramento",
		OptionsTooltipValuesAndUpgradesTooltip = "Mostra i valori di Pawn per tutte le tue formule visibili su tutti gli oggetti, eccetto quelli che hanno valore zero. In pi\195\185 indica quali oggetti sono un miglioramento al tuo attuale equipaggiamento.\
\
|cff8ec3e6Gelo:  123.4\
Fuoco:  156.7 |TInterface\\AddOns\\Pawn\\Textures\\UpgradeArrow:0|t |cff00ff00+10% di miglioramento|r",
		OptionsTooltipValuesOnly = "Mostra solo i valori della formula, nessuna % di miglioramento",
		OptionsTooltipValuesOnlyTooltip = "Mosta i valori di Pawn per tutte le tue formule visibili su tutti gli oggetti, eccetto quelli che hanno un valore di zero. Non indica quali oggessi sono un miglioramento per il tuo attuale equipaggiamento. Questa optione riflette il comportamento di default delle vecchie versioni di Pawn.\
\
|cff8ec3e6Gelo:  123.4\
Fuoco:  156.7|r",
		OptionsUpgradeHeader = "Mostra |TInterface\\AddOns\\Pawn\\Textures\\UpgradeArrow:0|t dei miglioramenti nei tooltip:",
		OptionsUpgradesForBothWeaponTypes = "Mostra miglioramenti sia per 1H che per 2H",
		OptionsUpgradesForBothWeaponTypesTooltip = "I suggerimenti di miglioramento di Pawn dovrebbero tracciare e mostrare i miglioramenti per le tue armi a 2 mani e le tue doppie armi (o per incantatori, mano principale e accessorio) separatamente.\
\
Se attivata, potresti usare un'arma a 2 mani e ancora vedere delle chiaramente inferiori armi ad 1 mano come un miglioramento se queste sono migliori delle precedenti migliori armi ad 1 mano che possedevi, perch\195\168 Pawn traccia separatamente i miglioramenti per i due tipi di armi.\
\
Se disattivata, equipaggiando un'arma a 2 mani impedir\195\160 a Pawn di mostrare i miglioramenti per oggetti ad una mano e vice versa.",
		OptionsWelcome = "Configura Pawn nella maniera che pi\195\185 ti aggrada. I cambiamenti avranno effetto immediatamente.",
		ScaleChangeColor = "Cambia colore",
		ScaleChangeColorTooltip = "Cambia il colore con cui il nome ed il valore di questa formula appariranno sul tooltip dell'oggetto.",
		ScaleCopy = "Copia",
		ScaleCopyTooltip = "Crea una nuova formula copiando questa.",
		ScaleDefaults = "Defaults",
		ScaleDefaultsTooltip = "Crea una nuova formula copiandola da quella di default.",
		ScaleDeleteTooltip = "Elimina questa formula.\
\
Questo comando non pu\195\178 essere annullato.",
		ScaleEmpty = "Vuota",
		ScaleEmptyTooltip = "Crea una nuova formula da zero.",
		ScaleExport = "Esporta",
		ScaleExportTooltip = "Condividi la tua formula con gli altri su internet.",
		ScaleHeader = "Gestisci le tue formule di Pawn",
		ScaleImport = "Importa",
		ScaleImportTooltip = "Aggiungi una nuova formula incollandola da internet.",
		ScaleNewHeader = "Crea una nuova formula",
		ScaleRename = "Rinomina",
		ScaleRenameTooltip = "Rinomina questa formula.",
		ScaleSelectorHeader = "Seleziona una formula:",
		ScaleSelectorShowScale = "Mostra la formula nei tooltip",
		ScaleSelectorShowScaleTooltip = "Quando questa opzione \195\168 attivata, i valori per questa formula verranno mostrati nei tooltip degli oggetti per questo personaggio. Ogni formula essere mostrata per uno dei tuoi personaggi, diversi personaggi o nessun personaggio.\
\
Scorciatoia: Shift+click su una formula",
		ScaleShareHeader = "Condividi le tue formule",
		ScaleTab = "Formula",
		ScaleTypeNormal = "Puoi modificare questa formula nella scheda Valori.",
		ScaleTypeReadOnly = "Devi fare una copia di questa formula se vuoi personalizzarla.",
		ScaleWelcome = "Le formule sono insiemi di statistiche e valori che sono usati per assegnare un punteggio agli oggetti. Puoi personalizzare la tua o usare i valori che altri hanno creato.",
		SocketingAdvisorButtonTooltip = "Clicca per aprire la scheda delle Gemme di Pawn, dove puoi avere maggiori informazioni sulle gemme che Pawn consiglia.",
		SocketingAdvisorHeader = "L'avviso d'Incavo di Pawn suggerisce:",
		SocketingAdvisorIgnoreThisItem = "Non disturbarti ad aggiungere gemme agli oggetti di basso livello. Ma se proprio vuoi, usa queste:",
		ValuesDoNotShowUpgradesFor1H = "Non mostrare miglioramenti per oggetti ad 1 mano",
		ValuesDoNotShowUpgradesFor2H = "Non mostrare miglioramenti per oggetti a 2 mani",
		ValuesDoNotShowUpgradesTooltip = "Abilita questa opzione per nascondere i miglioramenti di questo tipo di oggetto. Per esempio, anche se un difensore paladino pu\195\178 usare armi a 2 mani, un'arma a 2 mano non \195\168 mai un \"miglioramento\" per un paladino in assetto da difensore, quindi Pawn non dovrebbe mostrare la notifica di miglioramento per queste. In maniera similare, i paladini castigo possono usare armi ad 1 mano, ma non sono mai miglioramenti.",
		ValuesFollowSpecialization = "Mostra solo i miglioramenti per il mio miglior tipo di armatura dopo il livello 50",
		ValuesFollowSpecializationTooltip = "Abilita questa opzione per nascondere i miglioramenti dell'armatura in cui la tua classe non \195\168 specializzata dopo il livello 50. Per esempio, al livello 50 un paladino sacro impara Specializzazione: Armature a Piastre, che aumenta il proprio intelletto del 5% quando indossa solo armature in piastre. Quando questa opzione \195\168 selezionata Pawn non considerer\195\160 mai stoffa, pelle o maglia come miglioramenti per paladini sacri di livello 50+.",
		ValuesHeader = "Valori della formula per %s",
		ValuesIgnoreStat = "Gli oggetti con questa sono inutilizzabili",
		ValuesIgnoreStatTooltip = "Abilita questa opzione per far in modo che ogni oggetto con questa statistica non ottenga valore per questa formula. Per esempio, gli sciamani non possono indossare piastre, quindi una formula per uno sciamano pu\195\178 impostare piastre come inutilizzabile cos\195\172 che quelle armature non ottengano valore per quella formula.",
		ValuesNormalize = "Normalizza valori (come Wowhead)",
		ValuesNormalizeTooltip = "Abilita questa opzione per dividere il valore finale calcolato per un oggetto con la somma di tutti i valori delle statistiche nella tua formula, come Wowhead e Lootzor. Questo aiuta a livellare situazioni come quelle in cui una formula ha valori di statistiche attorno a 1 e un'altra ha valori attorno a 5. Aiuta anche a tenere i numeri maneggevolmente piccoli.\
\
Per maggiori informazioni su questa impostazione, leggere il file di readme.",
		ValuesRemove = "Rimuovi",
		ValuesRemoveTooltip = "Rimuovi questa statistica dalla formula.",
		ValuesTab = "Valori",
		ValuesWelcome = "Puoi personalizzare i valori che sono assegnati ad ogni statistica in questa formula. Per gestire le tue formule e aggiungerne di nuove, utilizza la scheda Formula.",
		ValuesWelcomeNoScales = "Non hai alcuna formula selezionata. Per iniziare, vai alla scheda Formula e crea una nuova formula o incollane una da internet.",
		ValuesWelcomeReadOnly = "La formula che hai selezionato non pu\195\178 essere cambiata. Se desideri cambiare questi valori, vai nella scheda Formula e fanne una copia o creane una nuova.",
	},
	Wowhead = {
		DeathKnightBloodTank = "CdM: sangue",
		DeathKnightFrostDps = "CdM: gelo",
		DeathKnightUnholyDps = "CdM: empiet\195\160",
		DruidBalance = "Druido: equilibrio",
		DruidFeralDps = "Druido: aggressore ferino",
		DruidFeralTank = "Druido: guardiano ferino",
		DruidRestoration = "Druido: rigenerazione",
		HunterBeastMastery = "Cacciatore: affinit\195\160 animale",
		HunterMarksman = "Cacciatore: precisione di tiro",
		HunterSurvival = "Cacciatore: sopravvivenza",
		MageArcane = "Mago: arcano",
		MageFire = "Mago: fuoco",
		MageFrost = "Mago: gelo",
		MonkBrewmaster = "Monaco: mastro birraio",
		MonkMistweaver = "Monaco: misticismo",
		MonkWindwalker = "Monaco: impeto",
		PaladinHoly = "Paladino: sacro",
		PaladinRetribution = "Paladino: castigo",
		PaladinTank = "Paladino: protezione",
		PriestDiscipline = "Sacerdote: disciplina",
		PriestHoly = "Sacerdote: sacro",
		PriestShadow = "Sacerdote: ombra",
		Provider = "Formule di Wowhead",
		ProviderStarter = "Formule per iniziare",
		RogueAssassination = "Ladro: assassinio",
		RogueCombat = "Ladro: combattimento",
		RogueSubtlety = "Ladro: scaltrezza",
		ShamanElemental = "Sciamano: elementale",
		ShamanEnhancement = "Sciamano: potenziamento",
		ShamanRestoration = "Sciamano: rigenerazione",
		WarlockAffliction = "Stregone: afflizione",
		WarlockDemonology = "Stregone: demonologia",
		WarlockDestruction = "Stregone: distruzione",
		WarriorArms = "Gurriero: armi",
		WarriorFury = "Gurriero: furia",
		WarriorTank = "Gurriero: protezione",
	},
}
end

if GetLocale() == "itIT" then
	PawnUseThisLocalization()
end

-- After using this localization or deciding that we don't need it, remove it from memory.
PawnUseThisLocalization = nil
