-- Generated by Babelfish script, do not add strings manually, only translate existing strings.
-- This is the base locale; values can be "true" so they default to their key, or any string to override that behaviour.
local L = LibStub("AceLocale-3.0"):NewLocale("LibMagicUtil-1.0", "enUS", true)


L["Background Color"] = true
L["Background Frame"] = true
L["Background Texture"] = true
L["Bar Height"] = true
L["Bar Scale"] = true
L["Bar Size"] = true
L["Bar Spacing"] = true
L["Bar Width"] = true
L["Border Texture"] = true
L["Border color"] = true
L["Edge size"] = true
L["Maximum number of bars"] = true
L["Number of pixels to insert between the background frame edge and the content."] = true
L["Padding"] = true
L["The background texture used for the background frame."] = true
L["The border texture used for the background frame."] = true
L["The size in pixels of the background tiles."] = true
L["The space in pixels between each bar."] = true
L["Tile Background"] = true
L["Tile Size"] = true
L["Whether or not to tile the background texture."] = true
L["Width of the border."] = true
