local L = LibStub("AceLocale-3.0"):NewLocale("GridStatusControlPipes", "enUS", true)

L["New "] = true
L["Adds a new guard of type "] = true
L["Adds a new filter of type "] = true
L["Guards"] = true
L["Guards control the piping state (piping or not piping)."] = true
L["Filters"] = true
L["Filters change the piped values."] = true
L["Control pipes"] = true
L["General settings for control pipes."] = true
L["New pipe"] = true
L["Creates a new pipe with the entered name."] = true
L["<unique pipe name>"] = true
L["Use pipe color"] = true
L["If enabled, it will use the color of the pipes status instead the color of the piped status."] = true
L["Remove - Reload UI!"] = true
L["Removes this pipe. You have to reload your UI after this!"] = true
L["Settings for pipe "] = true
L["Grid status control pipes - guard keys"] = true
L["Guard key "] = true
L["Settings for this guard"] = true
L["Settings for this filter"] = true
L["Key"] = true
L["The key binding to use."] = true
L["Sets the current binding for this key."] = true
L["Current binding"] = true
L["<key>"] = true
L["Remove"] = true
L["Removes this guard."] = true
L["Removes this filter."] = true
L["In combat piping"] = true
L["If enabled, the guard is open when in combat. Otherwise the guard is open out of combat."] = true
L["Threshold (in %)"] = true
L["Sets the threshold in percent when the guard should be open."] = true
L["Removes this aura."] = true
L["Enable"] = true
L["Toggle if this aura should be filtered."] = true
L["Options for aura: "] = true
L["Add new aura"] = true
L["Adds a new aura to be filtered."] = true
L["<aura name>"] = true
L["DRUID"] = "Druid"
L["PRIEST"] = "Priest"
L["WARRIOR"] = "Warrior"
L["ROGUE"] = "Rouge"
L["SHAMAN"] = "Shaman"
L["PALADIN"] = "Paladin"
L["MAGE"] = "Mage"
L["WARLOCK"] = "Warlock"
L["DEATHKNIGHT"] = "Death Knight"
L["HUNTER"] = "Hunter"
L["Opens pipe for this class."] = true
L["Status"] = true
L["The status which should be thresholded."] = true
L["Value"] = true
L["Duration"] = true
L["Stacks"] = true
L["Open when"] = true
L["Choose if the guard should be open if status is below or above the threshold."] = true
L["above"] = true
L["below"] = true
L["Threshold"] = true
L["Sets the threshold when the guard should be open."] = true
L["<threshold (in seconds in case of duration)>"] = true
L["The status which should be converted to text."] = true